# Generated by Django 3.2.9 on 2021-12-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="credits",
            field=models.PositiveIntegerField(verbose_name="Creditos"),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="level",
            field=models.CharField(
                choices=[
                    ("0", "Grátis"),
                    ("1", "Básico"),
                    ("2", "Intermediário"),
                    ("3", "Avançado"),
                ],
                max_length=1,
                unique=True,
                verbose_name="Nível do Plano",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Preço"),
        ),
        migrations.AlterField(
            model_name="usersubscriptionplan",
            name="credits_avaliable",
            field=models.PositiveIntegerField(verbose_name="Creditos"),
        ),
    ]
