# Generated by Django 3.2.9 on 2021-12-14 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0002_auto_20211209_1230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essaycorrection",
            name="competence_1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(limit_value=200)],
                verbose_name="Competência 1",
            ),
        ),
        migrations.AlterField(
            model_name="essaycorrection",
            name="competence_2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(limit_value=200)],
                verbose_name="Competência 2",
            ),
        ),
        migrations.AlterField(
            model_name="essaycorrection",
            name="competence_3",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(limit_value=200)],
                verbose_name="Competência 3",
            ),
        ),
        migrations.AlterField(
            model_name="essaycorrection",
            name="competence_4",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(limit_value=200)],
                verbose_name="Competência 4",
            ),
        ),
        migrations.AlterField(
            model_name="essaycorrection",
            name="competence_5",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(limit_value=200)],
                verbose_name="Competência 5",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(limit_value=0)],
                verbose_name="Preço",
            ),
        ),
    ]
