# Generated by Django 3.2.9 on 2021-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0003_auto_20211213_2237"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essaycorrection",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("IN PROGRESS", "Em progresso"),
                    ("COMPLETED", "Concluído"),
                    ("TIMEOUT", "Tempo de correção esgotado"),
                ],
                max_length=15,
                verbose_name="Status da correção",
            ),
        ),
    ]
