# Generated by Django 3.2.9 on 2021-12-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0005_auto_20211221_0148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essaycorrection",
            name="duration",
            field=models.DateField(null=True, verbose_name="Duração"),
        ),
    ]
