# Generated by Django 3.2.9 on 2021-12-21 12:31

import core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0006_alter_essaycorrection_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essaytheme",
            name="theme_file",
            field=models.FileField(
                upload_to=core.utils.models.file_upload_path,
                verbose_name="Texto de Apoio",
            ),
        ),
    ]
