# Generated by Django 3.2.9 on 2022-01-27 12:23

import core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essay", "0007_alter_essaytheme_theme_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscriptionplan",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="usersubscriptionplan",
            name="user",
        ),
        migrations.AlterField(
            model_name="essay",
            name="image",
            field=models.ImageField(
                default="default/essay-image.png",
                upload_to=core.utils.models.file_upload_path,
                verbose_name="Imagem da redação",
            ),
        ),
        migrations.AlterField(
            model_name="essaytheme",
            name="theme_file",
            field=models.FileField(
                default="default/essaytheme-file.pdf",
                upload_to=core.utils.models.file_upload_path,
                verbose_name="Texto de Apoio",
            ),
        ),
        migrations.DeleteModel(
            name="SubscriptionPlan",
        ),
        migrations.DeleteModel(
            name="UserSubscriptionPlan",
        ),
    ]
