# Generated by Django 3.2.9 on 2021-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
    ]
