# Generated by Django 3.2.9 on 2021-12-01 12:59

import core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="default/user-photo.png",
                upload_to=core.utils.models.file_upload_path,
                verbose_name="Foto",
            ),
        ),
    ]
